# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(max_length=45)),
                ('updated_at', models.DateTimeField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(max_length=45)),
                ('updated_at', models.DateTimeField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='LikesBooks_app.Users'),
        ),
        migrations.AddField(
            model_name='books',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='LikesBooks_app.Users'),
        ),
    ]
